# To render with this profile (will be merged with `_quarto.yml`), please run quarto render --profile zhtw
# See https://quarto.org/docs/projects/profiles.html
# KEYNOTE: A code block may result in ChatGPT translation output error. 
# To avoid this, please find all code blocks in the documents and manually 
# remove them before feeding the qmd script to ChatGPT. 
# Here is a helpful regular expression: ```.*\n+([\n\s\r]|.)*?```
project:
  output-dir: docs/zh-TW

website:
  title: "GEMS-MagTIP 說明文件中文版"
  navbar:
    left:
      - href: index.qmd
        text: 主頁
      - href: doc_tutorial/index.qmd
        text: 教程
      - href: doc_library/index.qmd
        text: 函式庫

      - about.qmd
