project:
  type: website
  output-dir: docs
# KEYNOTE: 
# - It is necessary to have docs/index.html, because 
#   I choose the folder /docs to be deployed on Github page.
#   In this project, I make profile `en` as default, and 
#   set its output-dir to docs.
website:
  title: "GEMS-MagTIP"
  page-footer:     
  # bottom bar
    left: "Copyright 2025, CGRG-lab and Tsung-Hsi Wu" 
  navbar: 
  # top bar
    right: 
    - icon: github
      href: https://github.com/okatsn/GEMS-MagTIP
    - icon: globe-americas
      href: ./
    - icon: translate
      href: ./zh-TW

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

profile:
  default: en
  # default profile when using `quarto render`
  # otherwise, you may need to run `quarto render --profile en`
  group: 
    - [en, zhtw]

