# To render with this profile (will be merged with `_quarto.yml`), please run quarto render --profile zhtw
# See https://quarto.org/docs/projects/profiles.html
project:
  output-dir: docs/zh-TW

website:
  navbar:
    left:
      - href: index.zh-TW.qmd
        text: 主頁
      - href: doc_tutorial/index.zh-TW.qmd
        text: 教程
      - href: doc_library/index.zh-TW.qmd
        text: 函式庫

      - about.zh-TW.qmd
