stages:
  # See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#stage-entries
  dvc_pull:
    # Initiate submodule is required in the beginning: git submodule update --init
    cmd: dvc pull
  dvc_pull_submodule:
    # Initiate submodule is required in the beginning: git submodule update --init
    cmd: git submodule update --remote GEMS-MagTIP-insider && dvc pull
    # https://stackoverflow.com/questions/1979167/git-submodule-update
    # KEYNOTE: In .gitmodules, in the field of submodule "GEMS-MagTIP-insider" I have manually added `branch = main`, so that no matter what branch is checked out in the local submodule, `git submodule update --remote` always
    wdir: GEMS-MagTIP-insider
    outs:
      - .gitmodules
  quarto_render:
    cmd: quarto render --profile en && quarto render --profile zhtw
    deps:
      - .gitmodules
      - assets
      - index.qmd
      - doc_library
      - doc_tutorial
